init:
  tzutil /s "Pacific Standard Time"

image:
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"
    - nodejs_version: ""

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run test

# Don't actually build.
build: off
